
INFO:root:Epoch 1
/home/brett/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Process Process-1:
Traceback (most recent call last):
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/brett/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/main_ijepa.py", line 62, in process_main
    app_main(args=params)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 380, in main
    val_loss = validate(val_loader, encoder, predictor=target_encoder)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/train.py", line 283, in validate
    outputs = predictor(context_embeddings, masks_enc, masks_pred)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/models/vision_transformer.py", line 409, in forward
    x = self.patch_embed(x)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/brett/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/brett/Desktop/tutorials/ijepa/ijepa/src/models/vision_transformer.py", line 187, in forward
    B, C, H, W = x.shape
ValueError: not enough values to unpack (expected 4, got 3)